name: Generate .deb (ceres)

on:
  schedule:
    - cron: "0 0 15 * *"
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Build DEB package
        uses: DevChall-by-SDCY-and-VXM/debian-buildpackage-template@main
        with:
          distro: ghcr.io/shadichy/aaropa_rootfs_base:main
          arch: amd64
          docker_arch_specific: true

      - name: Extract artifact
        run: unzip -o built-deb-files.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            metadata.yml
            *_*_*.buildinfo
            *_*_*.changes
            *_*_*.deb
            *_*_*.udeb

  release:
    name: Release
    needs: build
    if: ((github.event_name == 'push' || github.event_name == 'workflow_dispatch') && startsWith(github.ref, 'refs/tags/'))

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Download aaropa-calamares
        id: download-aaropa-calamares
        uses: actions/download-artifact@v4
        with:
          path: out
          pattern: "*"
          merge-multiple: true

      - name: List Files
        run: ls -R ${{ steps.download-aaropa-calamares.outputs.download-path }}

      - uses: "softprops/action-gh-release@v2.1.0"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{ steps.download-aaropa-calamares.outputs.download-path }}/*

  monthly-release:
    name: Monthly release
    needs: build
    if: (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Download aaropa-calamares
        id: download-aaropa-calamares
        uses: actions/download-artifact@v4
        with:
          path: out
          pattern: "*"
          merge-multiple: true
      - name: List Files
        run: ls -R ${{ steps.download-aaropa-calamares.outputs.download-path }}

      - uses: "softprops/action-gh-release@v2.1.0"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          tag_name: "r${{ github.run_number }}"
          name: "Monthly release r${{ github.run_number }}"
          files: |
            ${{ steps.download-aaropa-calamares.outputs.download-path }}/*
